### PR TITLE
Added more colors from the mod: More signal color

### PR DESCRIPTION
**Pull request by dunpealhunter**
Some of the colors were not working if you had the mod: More signal color. I fixed that.

### CODE REVIEW

**Comment by sparr** [comment]
This would be better handled by reading from the signal_to_color_mapping table on the lamp entity. That would work with the base game, as well as any mods that add more colors, including More Signal Color.

**Comment by sparr** [comment]
https://github.com/jfmmm/Factorio-more-signal-color/blob/master/prototypes/entity/entities.lua

**Comment by justarandomgeek** [comment]
I have no intention of supporting extra colors directly, ever (colors are most of the performance cost of numeric nixies currently, becuase it requires looking at/for so many signals). I'll probably be adding a remote.call() for other mods to register extra colors though, similar to how mods can register character translations for signals with signalstrings.

The signal_to_color_mapping table isn't available after data time, and I don't want to do dirty hacks to pass it around. Also, my colors aren't all exactly the same colors used for lamps. IIRC the blues at least got some tweaking to look less potato.

**Comment by justarandomgeek** [comment]
I've put in an API request to simply read the colors directly from the lamps, which will enable all colors that your game's lamps support, but I'm not sure if i've sufficiently convinced Rseding of it yet!

**Comment by justarandomgeek** [comment]
This request no longer applies - Nixie tubes now respect the signal coloring of the lamp directly, so any mods which extend that will work automatically.

**Pull request closed without merging**
